roland = {
    'sigz0': {'rename': 'sigz_over_one_plus_z'}, 
    'numdens1': {'rename': 'number_density_in_hinvMpc_1'}, 
    'numdens2': {'rename': 'number_density_in_hinvMpc_2'}, 
    'numdens3': {'rename': 'number_density_in_hinvMpc_3'}, 
    'numdens4': {'rename': 'number_density_in_hinvMpc_4'}, 
    'numdens5': {'rename': 'number_density_in_hinvMpc_5'}, 
    'galaxy_bias1': {'rename': 'galaxy_bias_1'}, 
    'galaxy_bias2': {'rename': 'galaxy_bias_2'}, 
    'galaxy_bias3': {'rename': 'galaxy_bias_3'}, 
    'galaxy_bias4': {'rename': 'galaxy_bias_4'}, 
    'galaxy_bias5': {'rename': 'galaxy_bias_5'}, 
    'zPk': {'rename': None},
    'npop': {'rename': 'nsample'},
    'Nzbin': {'rename': 'nz'}, 
    }

spherex_public = {
    'sigz0': {'rename': 'sigz_over_one_plus_z'}, 
    'numdens1': {'rename': 'number_density_in_hinvMpc_1'}, 
    'numdens2': {'rename': 'number_density_in_hinvMpc_2'}, 
    'numdens3': {'rename': 'number_density_in_hinvMpc_3'}, 
    'numdens4': {'rename': 'number_density_in_hinvMpc_4'}, 
    'numdens5': {'rename': 'number_density_in_hinvMpc_5'}, 
    'galaxy_bias1': {'rename': 'galaxy_bias_1'}, 
    'galaxy_bias2': {'rename': 'galaxy_bias_2'}, 
    'galaxy_bias3': {'rename': 'galaxy_bias_3'}, 
    'galaxy_bias4': {'rename': 'galaxy_bias_4'}, 
    'galaxy_bias5': {'rename': 'galaxy_bias_5'}, 
    'zPk': {'rename': None},
    'npop': {'rename': 'nsample'},
    'Nzbin': {'rename': 'nz'}, 
    }